name: Deploy Frontend to GitHub Pages

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Folosim un runner Ubuntu pe GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Check-out repo-ul

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Actualizează la o versiune compatibilă

      - name: Install dependencies
        run: |
          cd frontend      # Mergem în folderul frontend
          npm install --legacy-peer-deps  # Instalăm dependențele ignorând conflictele de peer dependency

      - name: Build frontend
        run: |
          cd frontend      # Mergem în folderul frontend
          npm run build    # Construim proiectul (vite va salva fișierele în dist/)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Folosim acțiunea gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token-ul GitHub pentru autentificare
          publish_dir: frontend/dist # Folderul care conține fișierele construite
